#### GET tasks

GET http://localhost:3000/tasks/6
Accept: application/json

#### POST tasks

POST http://localhost:3000/tasks
Accept: application/json
Content-Type: application/json

{
  "name": "new task",
  "due_date": "2022-08-12",
  "done": true,
  "list_id": 1,
  "description": "description of new task"
}


#### DELETE tasks

DELETE http://localhost:3000/tasks/3
Accept: application/json
Content-Type: application/json

#### PATCH tasks

PATCH http://localhost:3000/tasks/4
Accept: application/json
Content-Type: application/json

{
  "name": "Buy",
  "list_id": 3,
  "due_date": "2022-08-11"
}

#### PUT tasks

PUT http://localhost:3000/tasks/5
Accept: application/json
Content-Type: application/json

{
  "done": true
}

#### GET dashboard

GET http://localhost:3000/dashboard
Accept: application/json

#### GET today Tasks

GET http://localhost:3000/collection/today
Accept: application/json

#### GET tasks from list

GET http://localhost:3000/lists/1/tasks?all=true
Accept: application/json